apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
from apps.home import blueprint
from flask import render_template, request, url_for, redirect
from flask_login import login_required
from jinja2 import TemplateNotFound
from apps.authentication.models import Admin, User, Keluar, Masuk 
from apps.authentication.forms import UpdateUserAccount, UpdateAdminAccount
from apps import db

@blueprint.route('/index')
# @login_required
def index():
    
    return render_template('home/index.html', segment='index')


@blueprint.route('/<template>')
# @login_required
def route_template(template):
    
    admin = Admin.query.all()
    user = User.query.all()
    keluar = Keluar.query.all()
    masuk = Masuk.query.all()

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment, admin=admin, user=user, keluar=keluar, masuk=masuk)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None


#update

@blueprint.route('/user/<int:id>/update', methods = ['GET', 'POST'])
# @login_required
def updateuser(id):
    user = User.query.get_or_404(id)
    form = UpdateUserAccount()
    if form.validate_on_submit():
        user.username = form.username.data
        user.no_identitas = form.no_identitas.data
        user.nama = form.nama.data
        user.gender = form.gender.data
        user.status = form.status.data
        user.no_hp = form.no_hp.data
        user.email = form.email.data
        user.alamat = form.alamat.data
        user.no_plat = form.no_plat.data
        user.tanggal_masuk = form.tanggal_masuk.data
        user.password = form.password.data
        
        db.session.commit()
        return render_template('accounts/updateuser.html',
                               msg='User updated successfully <br> <a href="/user.html">User Page</a>',
                               success=True, id=user.id)
    form.username.data = user.username
    form.no_identitas.data = user.no_identitas
    form.nama.data = user.nama
    form.gender.data = user.gender
    form.status.data = user.status
    form.no_hp.data = user.no_hp
    form.email.data = user.email
    form.alamat.data = user.alamat
    form.no_plat.data = user.no_plat
    form.tanggal_masuk.data = user.tanggal_masuk
    form.password.data = user.password
    return render_template('accounts/updateuser.html', form=form)

@blueprint.route('/admin/<int:id>/update', methods = ['GET', 'POST'])
# @login_required
def updateadmin(id):
    admin = Admin.query.get_or_404(id)
    form = UpdateAdminAccount()
    if form.validate_on_submit():
        admin.username = form.username.data
        admin.no_identitas = form.no_identitas.data
        admin.nama = form.nama.data
        admin.gender = form.gender.data
        admin.no_hp = form.no_hp.data
        admin.email = form.email.data
        admin.tanggal_lahir = form.tanggal_lahir.data
        admin.alamat = form.alamat.data
        admin.tanggal_masuk = form.tanggal_masuk.data
        admin.password = form.password.data
        
        db.session.commit()
        return render_template('accounts/updateadmin.html',
                               msg='Admin updated successfully <br> <a href="/admin.html">Admin Page</a>',
                               success=True, id=admin.id)
    form.username.data = admin.username
    form.no_identitas.data = admin.no_identitas
    form.nama.data = admin.nama
    form.gender.data = admin.gender
    form.no_hp.data = admin.no_hp
    form.email.data = admin.email
    form.tanggal_lahir.data = admin.tanggal_lahir
    form.alamat.data = admin.alamat
    form.tanggal_masuk.data = admin.tanggal_masuk
    form.password.data = admin.password
    return render_template('accounts/updateadmin.html', form=form)
 
        
#delete
@blueprint.route('/deleteadmin/<int:id>')
def deleteadmin(id):
    admin = Admin.query.get_or_404(id)
    
    try:
        db.session.delete(admin)
        db.session.commit()
        return redirect(url_for('home_blueprint.index'))
    except:
        return redirect(url_for('home_blueprint.index'))
    
@blueprint.route('/deleteuser/<int:id>')
def deleteuser(id):
    user = User.query.get_or_404(id)
    
    try:
        db.session.delete(user)
        db.session.commit()
        return render_template('home/user.html')
    except:
        return redirect(url_for('home_blueprint.index'))
    
@blueprint.route('/deletekeluar/<int:id>')
def deletekeluar(id):
    keluar = Keluar.query.get_or_404(id)
    
    try:
        db.session.delete(keluar)
        db.session.commit()
        return render_template('home/keluar.html')
    except:
        return redirect(url_for('home_blueprint.index'))
    
@blueprint.route('/deletemasuk/<int:id>')
def deletemasuk(id):
    masuk = Masuk.query.get_or_404(id)
    
    try:
        db.session.delete(masuk)
        db.session.commit()
        return render_template('home/masuk.html')
    except:
        return redirect(url_for('home_blueprint.index'))
    

apps/templates/home/admin.html
{% extends 'layouts/base.html' %}

{% block title %} Daftar Admin {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Daftar Admin</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="/index"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Admin</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Daftar Admin</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
              <!--<a href="#" class="btn btn-sm btn-neutral">New</a>
              <a href="#" class="btn btn-sm btn-neutral">Filters</a>-->
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <div class="card">
          <!-- Card header -->
          <div class="card-header border-0">
            <h3 class="mb-0">Daftar Admin</h3>
          </div>
          <!-- Light table -->
          <div class="table-responsive">
            {% if admin %}
            <table class="table align-items-center table-flush text-center" >
              <thead class="thead-light">
                <tr>
                  <th>ID</th>
                  <th>No. Identitas</th>
                  <th>Nama</th>
                  <th>Jenis Kelamin</th>
                  <th>No. HP</th>
                  <th>Email</th>
                  <th>Tanggal Lahir</th>
                  <th>Alamat</th>
                  <th>Tanggal Masuk</th>
                  <th></th>
                </tr>
              </thead>
              <tbody class="list">
                {% for row in admin %}
                <tr>
                  <td> {{ row.id }} </td>
                  <td> {{ row.no_identitas }} </td>
                  <td> {{ row.nama }} </td>
                  <td> {{ row.gender }} </td>
                  <td> {{ row.no_hp }} </td>
                  <td> {{ row.email }} </td>
                  <td> {{ row.tanggal_lahir }} </td>
                  <td> {{ row.alamat }} </td>
                  <td> {{ row.tanggal_masuk }} </td>
                  <td class="text-right">
                    <form class="dropdown" action="" method="POST">
                      <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                        <a class="dropdown-item" href="{{ url_for('home_blueprint.updateadmin', id=row.id) }}">Edit</a>
                        <a class="dropdown-item" href="{{ url_for('home_blueprint.deleteadmin', id=row.id) }}">Delete</a>
                      </div> 
                    </form>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
          {% endif %}
        </div>
          <!-- Card footer -->
          <div class="card-footer py-4">
            <nav aria-label="...">
              <ul class="pagination justify-content-end mb-0">
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">
                    <i class="fas fa-angle-left"></i>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                <li class="page-item active">
                  <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">
                    <i class="fas fa-angle-right"></i>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>

    {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/chatbot.html
{% extends 'layouts/base.html' %}

{% block title %} Upload Manual {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Manual</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="/index"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Upload Manual</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Upload Manual Plat</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
              <!--<a href="#" class="btn btn-sm btn-neutral">New</a>
              <a href="#" class="btn btn-sm btn-neutral">Filters</a>-->
            </div>
          </div>
        </div>
      </div>
    </div>


    {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/keluar.html
{% extends 'layouts/base.html' %}

{% block title %} Keluar {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Keluar</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="/index"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Riwayat Keluar</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Keluar</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
              <!--<a href="#" class="btn btn-sm btn-neutral">New</a>
              <a href="#" class="btn btn-sm btn-neutral">Filters</a>-->
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <div class="card">
          <!-- Card header -->
          <div class="card-header border-0">
            <h3 class="mb-0">Riwayat Keluar Kendaraan</h3>
          </div>
          <!-- Light table -->
          <div class="table-responsive">
            {% if keluar %}
            <table class="table align-items-center table-flush text-center">
              <thead class="thead-light">
                <tr>
                  <th>ID</th>
                  <th>No. Identitas</th>
                  <th>Nama</th>
                  <th>Status</th>
                  <th>No. HP</th>
                  <th>Alamat</th>
                  <th>No. Plat</th>
                  <th>Waktu Keluar</th>
                  <th></th>
                </tr>
              </thead>
              <tbody class="list">
                {% for row in keluar %}
                <tr>
                  <td> {{ row.id }} </td>
                  <td> {{ row.no_identitas }} </td>
                  <td> {{ row.nama }} </td>
                  <td> {{ row.status }} </td>
                  <td> {{ row.no_hp }} </td>
                  <td> {{ row.alamat }} </td>
                  <td> {{ row.no_plat }} </td>
                  <td> {{ row.waktu_keluar }} </td>
                  <td class="text-right">
                    <div class="dropdown">
                      <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                        <a class="dropdown-item" href="{{ url_for('home_blueprint.deletekeluar', id=row.id) }}">Delete</a>
                      </div>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% endif %}
          </div>
          <!-- Card footer -->
          <div class="card-footer py-4">
            <nav aria-label="...">
              <ul class="pagination justify-content-end mb-0">
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">
                    <i class="fas fa-angle-left"></i>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                <li class="page-item active">
                  <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">
                    <i class="fas fa-angle-right"></i>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>

    {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/masuk.html
{% extends 'layouts/base.html' %}

{% block title %} Masuk {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Masuk</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="/index"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Riwayat Masuk</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Masuk</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
              <!--<a href="#" class="btn btn-sm btn-neutral">New</a>
              <a href="#" class="btn btn-sm btn-neutral">Filters</a>-->
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <div class="card">
          <!-- Card header -->
          <div class="card-header border-0">
            <h3 class="mb-0">Riwayat Masuk Kendaraan</h3>
          </div>
          <!-- Light table -->
          <div class="table-responsive">
            {% if masuk %}
            <table class="table align-items-center table-flush text-center">
              <thead class="thead-light">
                <tr>
                  <th>ID</th>
                  <th>No. Identitas</th>
                  <th>Nama</th>
                  <th>Status</th>
                  <th>No. HP</th>
                  <th>Alamat</th>
                  <th>No. Plat</th>
                  <th>Waktu Masuk</th>
                  <th></th>
                </tr>
              </thead>
              <tbody class="list">
                {% for row in masuk %}
                <tr>
                  <td> {{ row.id }} </td>
                  <td> {{ row.no_identitas }} </td>
                  <td> {{ row.nama }} </td>
                  <td> {{ row.status }} </td>
                  <td> {{ row.no_hp }} </td>
                  <td> {{ row.alamat }} </td>
                  <td> {{ row.no_plat }} </td>
                  <td> {{ row.waktu_masuk }} </td>
                  <td class="text-right">
                    <div class="dropdown">
                      <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                        <a class="dropdown-item" href="{{ url_for('home_blueprint.deletemasuk', id=row.id) }}">Delete</a>
                      </div>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% endif %}
          </div>
          <!-- Card footer -->
          <div class="card-footer py-4">
            <nav aria-label="...">
              <ul class="pagination justify-content-end mb-0">
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">
                    <i class="fas fa-angle-left"></i>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                <li class="page-item active">
                  <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">
                    <i class="fas fa-angle-right"></i>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>

    {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-403.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 403      
              </div>

              <div class="text-center mb-4">
                Access denied - Please authenticate <a href="{{ url_for('authentication_blueprint.login') }}">Login</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>          
            <!--<div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>-->
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://instagram.com/srndhn23_?utm_medium=copy_link" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 404      
              </div>

              <div class="text-center mb-4">
                Page not found - <a href="/">Home</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://instagram.com/srndhn23_?utm_medium=copy_link" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 500      
              </div>

              <div class="text-center mb-4">
                Server error, please contact support - <a href="/">Home</a>.
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://instagram.com/srndhn23_?utm_medium=copy_link" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/uploadmanual.html
{% extends 'layouts/base.html' %}

{% block title %} Upload Manual {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Manual</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Upload Manual</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Upload Manual Plat</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
              <a href="#" class="btn btn-sm btn-neutral">New</a>
              <a href="#" class="btn btn-sm btn-neutral">Filters</a>
            </div>
          </div>
        </div>
      </div>
    </div>


    {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/user.html
{% extends 'layouts/base.html' %}

{% block title %} User {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Daftar User</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="/index"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">User</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Daftar User</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
              <!--<a href="#" class="btn btn-sm btn-neutral">New</a>
              <a href="#" class="btn btn-sm btn-neutral">Filters</a>-->
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <div class="card">
          <!-- Card header -->
          <div class="card-header border-0">
            <h3 class="mb-0">Daftar Users</h3>
          </div>
          <!-- Light table -->
          <div class="table-responsive">
            {% if user %}
            <table class="table align-items-center table-flush text-center">
              <thead class="thead-light">
                <tr>
                  <th></th>
                  <th>Username</th>
                  <th>No. Identitas</th>
                  <th>Nama</th>
                  <th>Jenis Kelamin</th>
                  <th>Status</th>
                  <th>No. HP</th>
                  <th>Email</th>
                  <th>Alamat</th>
                  <th>No. Plat</th>
                  <!--<th>STNK</th>-->
                  <th>Tanggal Masuk</th>
                  <th></th>
                </tr>
              </thead>
              <tbody class="list">
                {% for row in user %}
                <tr>
                  <td> {{ row.id }} </td>
                  <td> {{ row.username }} </td>
                  <td> {{ row.no_identitas }} </td>
                  <td> {{ row.nama }} </td>
                  <td> {{ row.gender }} </td>
                  <td> {{ row.status }} </td>
                  <td> {{ row.no_hp }} </td>
                  <td> {{ row.email }} </td>
                  <td> {{ row.alamat }} </td>
                  <td> {{ row.no_plat }} </td>
                  <td> {{ row.tanggal_masuk }} </td>
                  <td class="text-right">
                    <div class="dropdown">
                      <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                        <a class="dropdown-item" href="{{ url_for('home_blueprint.updateuser', id=row.id) }}">Edit</a>
                        <a class="dropdown-item" href="{{ url_for('home_blueprint.deleteuser', id=row.id) }}">Delete</a>
                      </div>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% endif %}
          </div>
          <!-- Card footer -->
          <div class="card-footer py-4">
            <nav aria-label="...">
              <ul class="pagination justify-content-end mb-0">
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">
                    <i class="fas fa-angle-left"></i>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                <li class="page-item active">
                  <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">
                    <i class="fas fa-angle-right"></i>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>

    {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}